AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Calculates total amount contributed during a campaign, for use by a ticker

Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: support
  App:
    Description: Application name
    Type: String
    Default: contributions-ticker-calculator
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
  DeployBucket:
    Description: Bucket to copy files to
    Type: String
    Default: contributions-dist
  AcquisitionEventsBucket:
    Description: Bucket containing the data to be queried
    Type: String
    Default: acquisition-events
  AthenaOutputBucket:
    Description: Name of the bucket to output athena query results to
    Type: String
  SchemaName:
    Description: The schema name for the query
    Type: String
    Default: acquisition
  InitialAmount:
    Description: Amount to add to the result of the query
    Type: Number
    Default: 0
  CountryCodes:
    Description: List of country codes, e.g. 'US,AU'
    Type: CommaDelimitedList

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${App}-${Stage}
      Description: Calculates total amount contributed during a campaign, for use by a ticker
      Runtime: nodejs8.10
      Handler: lambda.handler
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          Stage: !Ref Stage
          AcquisitionEventsBucket: !Ref AcquisitionEventsBucket
          AthenaOutputBucket: !Ref AthenaOutputBucket
          SchemaName: !Ref SchemaName
          InitialAmount: !Ref InitialAmount
          CountryCodes: !Ref CountryCodes
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/${App}/${App}.zip
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListObjects
            Resource:
              !Ref AcquisitionEventsBucket
        - Statement:
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListObjects
            Resource:
              !Sub "arn:aws:s3::*:${AthenaOutputBucket}"
