name: Snyk

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: true
      ORG: guardian-growth
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

